version: '3.8'

services:
  tgbot:
    build:
      context: .
      dockerfile: Dockerfile.tgbot
    depends_on:
      - postgres
    environment:
      TELEGRAM_TOKEN: "<token>"
      DATABASE_URI: "postgresql://user:password@postgres:5432/tgbot?sslmode=disable"
      UPDATE_INTERVAL: 3s
    networks:
      - my-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tgbot
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres-data:
    driver: local

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
